language: sh
services: docker
jobs:
  include:
  - script: docker run maven:slim /bin/sh -c "apt-get update && apt-get install --yes git && git clone --depth 50 --recurse-submodules --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git && cd labfolder-code-challenge && mvn install && cd labfolder-code-challenge-core && JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn -Dtest=de.richtercloud.labfolder.code.challenge.it.LabfolderCodeChallengeIT surefire:test"
